Update pr_checklist.yml

diff --git a/.github/workflows/pr_checklist.yml b/.github/workflows/pr_checklist.yml
--- a/.github/workflows/pr_checklist.yml
+++ b/.github/workflows/pr_checklist.yml
@@ -15,31 +15,33 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Get PR Description
+        id: get_pr_description
         run: |
           PR_NUMBER=${{ github.event.pull_request.number }}
           PR_DESCRIPTION=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" | \
                            jq -r '.body')
-
-          echo "::set-output name=pr_description::$PR_DESCRIPTION"
+          echo "PR_DESCRIPTION=$PR_DESCRIPTION" >> $GITHUB_ENV
 
       - name: Validate Checklist
         run: |
+          pr_description="${{ steps.get_pr_description.outputs.PR_DESCRIPTION }}"
+
           uncheckedItems=()
-          pr_description="${{ steps.get_pr_description.outputs.pr_description }}"
-
-          while IFS= read -r line; do
-            if [[ "$line" == *" - [ ] "* ]]; then
-              uncheckedItems+=("$line")
+          while read -r line; do
+            if [[ "$line" =~ "- \[ \] " ]]; then
+              uncheckedItems+=("${line//- \[ \] /}")
             fi
-          done <<< "${pr_description}"
+          done <<< "$pr_description"
 
-          if [ ${#uncheckedItems[@]} -gt 0 ]; then
-            echo "Unchecked items detected in PR checklist:"
+          uncheckedItemCount=${#uncheckedItems[@]}
+          if [ $uncheckedItemCount -gt 0 ]; then
             for item in "${uncheckedItems[@]}"; do
-              echo "$item"
+              if ! echo "$pr_description" | grep -qF "$item"; then
+                echo "Error: '$item' not found in checklist."
+                exit 1
+              fi
             done
-            exit 1
           else
             echo "All checklist items are checked in PR"
           fi
